# Web Scraping Car delaer website

Imports

In [13]:
from bs4 import BeautifulSoup
import requests
import pandas as pd


HTTP Request

store website in variable

In [37]:
website = "https://www.cars.com/shopping/results/?stock_type=all&makes%5B%5D=tesla&models%5B%5D=&list_price_max=&maximum_distance=all&zip="

Get Request

In [38]:
response = requests.get(website)

Status Code

In [39]:
response.status_code

200

Soup Object

In [40]:
soup = BeautifulSoup(response.content, 'html.parser')

Results

In [41]:
results = soup.find_all('div', {'class' : 'vehicle-card'})

In [42]:
len(results)

21

Target necessary data

In [43]:
# Name
# Dealer Name
# Rating
# Rating Count
# Price

Name

In [44]:
results[0].find('h2').get_text()

'2021 Tesla Model X Long Range'

Dealer Name

In [53]:
results[0].find('div', {'class':'dealer-name'}).get_text().strip

Rating

In [47]:
results[0].find('span', {'class':'sds-rating__count'}).get_text()

'3.9'

Review Count

In [49]:
results[0].find('span', {'class':'sds-rating__link'}).get_text()

'(87 reviews)'

Price

In [50]:
results[0].find('span', {'class':'primary-price'}).get_text()

'$80,887'

# Put everything together inside a For-Loop

In [55]:
name = []
dealer_name = []
rating = []
review_count = []
price = []

for result in results:
    
    # name
    try:
        name.append(result.find('h2').get_text()) 
    except:
        name.append('n/a')
    
    # dealer_name
    try:
        dealer_name.append(result.find('div', {'class':'dealer-name'}).get_text().strip())
    except:
        dealer_name.append('n/a')
        
    # rating
    try:
        rating.append(result.find('span', {'class':'sds-rating__count'}).get_text())
    except:
        rating.append('n/a')
    
    # review_count
    try:
        review_count.append(result.find('span', {'class':'sds-rating__link'}).get_text())
    except:
        review_count.append('n/a')
    
    #price 
    try:
        price.append(result.find('span', {'class':'primary-price'}).get_text())
    except:
        price.append('n/a')

# Create Pandas Dataframe

In [56]:
# dictionary
car_dealer = pd.DataFrame({'Name': name, 'Dealer Name':dealer_name,
                                'Rating': rating, 'Review Count': review_count, 'Price': price})

In [57]:
car_dealer

,Name,Dealer Name,Rating,Review Count,Price
0,2021 Tesla Model X Long Range,Volkswagen of Palm Springs,3.9,(87 reviews),"$80,887"
1,2022 Tesla Model Y Performance,Fox Ford of Chicago,4.7,"(1,733 reviews)","$56,726"
2,2018 Tesla Model S 75D,Naples INFINITI,4.9,(747 reviews),"$42,999"
3,2022 Tesla Model 3 Long Range,Cowboy Chrysler Dodge Jeep Ram,4.4,(35 reviews),"$47,529"
4,2013 Tesla Model S Base,Inside Car Guys LLC,n/a,(1 review),"$27,499"
5,2020 Tesla Model Y Long Range,CarMax Tallahassee - Offering Express Pickup a...,n/a,(3 reviews),"$46,998"
6,2021 Tesla Model S Plaid,CarMax Boise (Meridian) - Offering Express Pic...,n/a,(4 reviews),"$94,998"
7,2020 Tesla Model 3 Standard Range Plus,Capitol Chevrolet AL,4.8,(248 reviews),"$30,996"
8,2017 Tesla Model S P100D,n/a,n/a,n/a,"$55,498"
9,2017 Tesla Model S 75,Capital Ford,4.3,"(1,671 reviews)","$37,840"
10,2021 Tesla Model S Plaid,BMW of Eugene,4.5,(102 reviews),"$96,750"
11,2016 Tesla Model S 90D,Auto Valley Group,n/a,(4 reviews),"$41,990"
12,2019 Tesla Model X Long Range,JTs Dodgeland of Columbia Dodge RAM,4.2,(861 reviews),"$55,990"
13,2023 Tesla Model Y Performance,Westcott Automotive,n/a,(64 reviews),"$59,770"
14,2022 Tesla Model X LONG RANG,Foreign Cars Italia,4.9,"(1,313 reviews)","$109,990"
15,2022 Tesla Model S Base,Audi Flatirons,4.8,"(1,159 reviews)","$82,635"
16,2021 Tesla Model 3 Long Range,McCarthy Toyota of Sedalia,3.9,(110 reviews),"$41,739"
17,2020 Tesla Model 3 Long Range,Boulevard Ford Lincoln,n/a,(258 reviews),"$36,800"
18,2021 Tesla Model 3 Performance,Corwin Ford Reno,4.6,(444 reviews),"$46,989"
19,2018 Tesla Model 3 Long Range,Ryan Friedman Motor Cars,4.9,(22 reviews),"$34,995"
20,2020 Tesla Model X Long Range Plus,Cars Land,4.2,(6 reviews),"$69,500"

Data Cleaning

In [58]:
car_dealer['Review Count'] = car_dealer['Review Count'].apply(lambda x: x.strip('reviews)').strip('('))

In [59]:
car_dealer

,Name,Dealer Name,Rating,Review Count,Price
0,2021 Tesla Model X Long Range,Volkswagen of Palm Springs,3.9,87,"$80,887"
1,2022 Tesla Model Y Performance,Fox Ford of Chicago,4.7,"1,733","$56,726"
2,2018 Tesla Model S 75D,Naples INFINITI,4.9,747,"$42,999"
3,2022 Tesla Model 3 Long Range,Cowboy Chrysler Dodge Jeep Ram,4.4,35,"$47,529"
4,2013 Tesla Model S Base,Inside Car Guys LLC,n/a,1,"$27,499"
5,2020 Tesla Model Y Long Range,CarMax Tallahassee - Offering Express Pickup a...,n/a,3,"$46,998"
6,2021 Tesla Model S Plaid,CarMax Boise (Meridian) - Offering Express Pic...,n/a,4,"$94,998"
7,2020 Tesla Model 3 Standard Range Plus,Capitol Chevrolet AL,4.8,248,"$30,996"
8,2017 Tesla Model S P100D,n/a,n/a,n/a,"$55,498"
9,2017 Tesla Model S 75,Capital Ford,4.3,"1,671","$37,840"
10,2021 Tesla Model S Plaid,BMW of Eugene,4.5,102,"$96,750"
11,2016 Tesla Model S 90D,Auto Valley Group,n/a,4,"$41,990"
12,2019 Tesla Model X Long Range,JTs Dodgeland of Columbia Dodge RAM,4.2,861,"$55,990"
13,2023 Tesla Model Y Performance,Westcott Automotive,n/a,64,"$59,770"
14,2022 Tesla Model X LONG RANG,Foreign Cars Italia,4.9,"1,313","$109,990"
15,2022 Tesla Model S Base,Audi Flatirons,4.8,"1,159","$82,635"
16,2021 Tesla Model 3 Long Range,McCarthy Toyota of Sedalia,3.9,110,"$41,739"
17,2020 Tesla Model 3 Long Range,Boulevard Ford Lincoln,n/a,258,"$36,800"
18,2021 Tesla Model 3 Performance,Corwin Ford Reno,4.6,444,"$46,989"
19,2018 Tesla Model 3 Long Range,Ryan Friedman Motor Cars,4.9,22,"$34,995"
20,2020 Tesla Model X Long Range Plus,Cars Land,4.2,6,"$69,500"

Output in Excel

In [60]:
car_dealer.to_excel('car_dealer_single_page.xlsx', index=False)

Pagination

In [61]:
name = []
mileage = []
dealer_name = []
rating = []
review_count = []
price = []

for i in range (1,11):
    
    # website in variable
    website = 'https://www.cars.com/shopping/results/?page='+ str(i) +'&page_size=20&dealer_id=&list_price_max=&list_price_min=&makes[]=mercedes_benz&maximum_distance=20&mileage_max=&sort=best_match_desc&stock_type=cpo&year_max=&year_min=&zip=' 
    
    # request to website
    response = requests.get(website)
    
    # soup object
    soup = BeautifulSoup(response.content, 'html.parser')
    
    # results
    results = soup.find_all('div', {'class' : 'vehicle-card'})
    
    # loop through results
    for result in results:
    
        # name
        try:
            name.append(result.find('h2').get_text()) 
        except:
            name.append('n/a')

        # mileage
        try:
            mileage.append(result.find('div', {'class':'mileage'}).get_text())
        except:
            mileage.append('n/a')

        # dealer_name
        try:
            dealer_name.append(result.find('div', {'class':'dealer-name'}).get_text().strip())
        except:
            dealer_name.append('n/a')

        # rating
        try:
            rating.append(result.find('span', {'class':'sds-rating__count'}).get_text())
        except:
            rating.append('n/a')

        # review_count
        try:
            review_count.append(result.find('span', {'class':'sds-rating__link'}).get_text())
        except:
            review_count.append('n/a')

        #price 
        try:
            price.append(result.find('span', {'class':'primary-price'}).get_text())
        except:
            price.append('n/a')

In [62]:
# dictionary
car_dealer = pd.DataFrame({'Name': name, 'Mileage':mileage, 'Dealer Name':dealer_name,
                                'Rating': rating, 'Review Count': review_count, 'Price': price})

In [63]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz GLA 250 Base 4MATIC,"32,227 mi.",Mercedes-Benz of Centerville,4.7,(35 reviews),"$35,903"
1,2021 Mercedes-Benz E-Class E 450 4MATIC,"10,927 mi.",Mercedes-Benz of Raleigh,5.0,"(1,700 reviews)","$67,985"
2,2020 Mercedes-Benz GLE 350 Base 4MATIC,"46,567 mi.",Napleton Autowerks Loves Park,4.9,(839 reviews),"$46,999"
3,2019 Mercedes-Benz AMG S 63 Base 4MATIC,"45,954 mi.",Mercedes-Benz of Nashville,4.4,(894 reviews),"$88,927"
4,2016 Mercedes-Benz E-Class E 400,"34,794 mi.",Mercedes-Benz of Baton Rouge,5.0,(844 reviews),"$29,952"
...,...,...,...,...,...,...
197,2020 Mercedes-Benz SLC 300 Base,"27,606 mi.",RBM of Atlanta,4.2,"(1,025 reviews)","$45,843"
198,2018 Mercedes-Benz GLS 450 Base 4MATIC,"39,498 mi.",Mercedes-Benz of Delray,4.5,"(1,634 reviews)","$44,884"
199,2021 Mercedes-Benz AMG G 63 Base,"35,027 mi.",Mercedes-Benz Of Tampa,4.1,"(3,507 reviews)","$203,562"
200,2021 Mercedes-Benz AMG E 53 Base 4MATIC,"6,405 mi.",Mercedes-Benz of San Francisco / Smart Center ...,n/a,(62 reviews),"$76,988"
201,2017 Mercedes-Benz AMG C 63 S,"28,205 mi.",Mercedes-Benz of Northwest Arkansas,n/a,(45 reviews),"$56,068"

In [64]:
car_dealer['Review Count'] = car_dealer['Review Count'].apply(lambda x: x.strip('reviews)').strip('('))

In [65]:
car_dealer

,Name,Mileage,Dealer Name,Rating,Review Count,Price
0,2021 Mercedes-Benz GLA 250 Base 4MATIC,"32,227 mi.",Mercedes-Benz of Centerville,4.7,35,"$35,903"
1,2021 Mercedes-Benz E-Class E 450 4MATIC,"10,927 mi.",Mercedes-Benz of Raleigh,5.0,"1,700","$67,985"
2,2020 Mercedes-Benz GLE 350 Base 4MATIC,"46,567 mi.",Napleton Autowerks Loves Park,4.9,839,"$46,999"
3,2019 Mercedes-Benz AMG S 63 Base 4MATIC,"45,954 mi.",Mercedes-Benz of Nashville,4.4,894,"$88,927"
4,2016 Mercedes-Benz E-Class E 400,"34,794 mi.",Mercedes-Benz of Baton Rouge,5.0,844,"$29,952"
...,...,...,...,...,...,...
197,2020 Mercedes-Benz SLC 300 Base,"27,606 mi.",RBM of Atlanta,4.2,"1,025","$45,843"
198,2018 Mercedes-Benz GLS 450 Base 4MATIC,"39,498 mi.",Mercedes-Benz of Delray,4.5,"1,634","$44,884"
199,2021 Mercedes-Benz AMG G 63 Base,"35,027 mi.",Mercedes-Benz Of Tampa,4.1,"3,507","$203,562"
200,2021 Mercedes-Benz AMG E 53 Base 4MATIC,"6,405 mi.",Mercedes-Benz of San Francisco / Smart Center ...,n/a,62,"$76,988"
201,2017 Mercedes-Benz AMG C 63 S,"28,205 mi.",Mercedes-Benz of Northwest Arkansas,n/a,45,"$56,068"

In [66]:
car_dealer.to_excel('car_dealer_single_page.xlsx', index=False)